apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v31mf58mj-go 
  janus-idp.io/tekton: v31mf58mj-go
  backstage.io/kubernetes-id: v31mf58mj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v31mf58mj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml