apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v31mf58mj-go
  janus-idp.io/tekton: v31mf58mj-go
  backstage.io/kubernetes-id: v31mf58mj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v31mf58mj-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
