apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v31mf58mj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v31mf58mj-go 
  name: v31mf58mj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v31mf58mj-go 
